
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 26 20:50:16 ART 2015
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 18;
  public static final int MULT = 15;
  public static final int RT_P = 23;
  public static final int RET = 13;
  public static final int SEMI = 20;
  public static final int CONTINUE = 12;
  public static final int INT = 38;
  public static final int RT_B = 25;
  public static final int LESS = 28;
  public static final int FOR = 8;
  public static final int MINUS = 17;
  public static final int NOT = 31;
  public static final int AND = 2;
  public static final int OR = 9;
  public static final int COMMA = 21;
  public static final int CLASS = 10;
  public static final int AUTODEC = 35;
  public static final int DIV = 19;
  public static final int BEGIN = 4;
  public static final int EXTERN = 14;
  public static final int PLUS = 16;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int BOOLEAN = 37;
  public static final int EOF = 0;
  public static final int GTR = 27;
  public static final int LEFT_P = 22;
  public static final int error = 1;
  public static final int IDENT = 44;
  public static final int BREAK = 11;
  public static final int VOID = 40;
  public static final int EQ = 26;
  public static final int ASSMNT = 33;
  public static final int floatLiteral = 43;
  public static final int LEFT_B = 24;
  public static final int boolLiteral = 41;
  public static final int ELSE = 5;
  public static final int NOT_EQ = 32;
  public static final int WHILE = 3;
  public static final int LESS_EQ = 29;
  public static final int FLOAT = 39;
  public static final int intLiteral = 42;
  public static final int END = 6;
  public static final int GTR_EQ = 30;
  public static final int AUTOIN = 34;
}

